version: '3.8'

services:
  outlook-manager:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_MYSQL=mysql://outlook_user:outlook_password@mysql:3306/outlook_db
      - ADMIN_PASSWORD=admin123
    depends_on:
      - mysql
    volumes:
      - ./static:/app/static
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: outlook_db
      MYSQL_USER: outlook_user
      MYSQL_PASSWORD: outlook_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: